// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringApp.Data;

#nullable disable

namespace MonitoringApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringApp.Models.DataRealtime", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DataCh1")
                        .HasColumnType("time")
                        .HasColumnName("dataCh1");

                    b.Property<float>("DurasiTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("durasiTerakhirA4");

                    b.Property<DateTime>("Last_Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NilaiA0")
                        .HasColumnType("int")
                        .HasColumnName("nilaiA0");

                    b.Property<int>("NilaiTerakhirA2")
                        .HasColumnType("int")
                        .HasColumnName("nilaiTerakhirA2");

                    b.Property<int>("P_DataCh1")
                        .HasColumnType("int")
                        .HasColumnName("p_datach1");

                    b.Property<int>("P_Uptime")
                        .HasColumnType("int")
                        .HasColumnName("p_uptime");

                    b.Property<int>("PartHours")
                        .HasColumnType("int")
                        .HasColumnName("parthours");

                    b.Property<float>("RataRataTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("ratarataTerakhirA4");

                    b.Property<TimeSpan>("Uptime")
                        .HasColumnType("time")
                        .HasColumnName("uptime");

                    b.HasKey("Id");

                    b.ToTable("data_realtime", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Line1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("line");

                    b.Property<string>("LineProduction")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("line_production");

                    b.Property<int>("MachineCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("process");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("remark");

                    b.HasKey("Id");

                    b.ToTable("line", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.Models.Shift1", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DataCh1")
                        .HasColumnType("time")
                        .HasColumnName("dataCh1");

                    b.Property<float>("DurasiTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("durasiTerakhirA4");

                    b.Property<DateTime>("Last_Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NilaiA0")
                        .HasColumnType("int")
                        .HasColumnName("nilaiA0");

                    b.Property<int>("NilaiTerakhirA2")
                        .HasColumnType("int")
                        .HasColumnName("nilaiTerakhirA2");

                    b.Property<int>("P_DataCh1")
                        .HasColumnType("int")
                        .HasColumnName("p_datach1");

                    b.Property<int>("P_Uptime")
                        .HasColumnType("int")
                        .HasColumnName("p_uptime");

                    b.Property<int>("PartHours")
                        .HasColumnType("int")
                        .HasColumnName("parthours");

                    b.Property<float>("RataRataTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("ratarataTerakhirA4");

                    b.Property<TimeSpan>("Uptime")
                        .HasColumnType("time")
                        .HasColumnName("uptime");

                    b.HasKey("Id");

                    b.ToTable("shift_1", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.Models.Shift2", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DataCh1")
                        .HasColumnType("time")
                        .HasColumnName("dataCh1");

                    b.Property<float>("DurasiTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("durasiTerakhirA4");

                    b.Property<DateTime>("Last_Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NilaiA0")
                        .HasColumnType("int")
                        .HasColumnName("nilaiA0");

                    b.Property<int>("NilaiTerakhirA2")
                        .HasColumnType("int")
                        .HasColumnName("nilaiTerakhirA2");

                    b.Property<int>("P_DataCh1")
                        .HasColumnType("int")
                        .HasColumnName("p_datach1");

                    b.Property<int>("P_Uptime")
                        .HasColumnType("int")
                        .HasColumnName("p_uptime");

                    b.Property<int>("PartHours")
                        .HasColumnType("int")
                        .HasColumnName("parthours");

                    b.Property<float>("RataRataTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("ratarataTerakhirA4");

                    b.Property<TimeSpan>("Uptime")
                        .HasColumnType("time")
                        .HasColumnName("uptime");

                    b.HasKey("Id");

                    b.ToTable("shift_2", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.Models.Shift3", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DataCh1")
                        .HasColumnType("time")
                        .HasColumnName("dataCh1");

                    b.Property<float>("DurasiTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("durasiTerakhirA4");

                    b.Property<DateTime>("Last_Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NilaiA0")
                        .HasColumnType("int")
                        .HasColumnName("nilaiA0");

                    b.Property<int>("NilaiTerakhirA2")
                        .HasColumnType("int")
                        .HasColumnName("nilaiTerakhirA2");

                    b.Property<int>("P_DataCh1")
                        .HasColumnType("int")
                        .HasColumnName("p_datach1");

                    b.Property<int>("P_Uptime")
                        .HasColumnType("int")
                        .HasColumnName("p_uptime");

                    b.Property<int>("PartHours")
                        .HasColumnType("int")
                        .HasColumnName("parthours");

                    b.Property<float>("RataRataTerakhirA4")
                        .HasColumnType("real")
                        .HasColumnName("ratarataTerakhirA4");

                    b.Property<TimeSpan>("Uptime")
                        .HasColumnType("time")
                        .HasColumnName("uptime");

                    b.HasKey("Id");

                    b.ToTable("shift_3", (string)null);
                });

            modelBuilder.Entity("MonitoringApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
